name: 'Setup A.R.C. Docker Environment'
description: 'Setup Docker with GHCR login, BuildKit, and cache configuration for A.R.C. builds'

inputs:
  registry:
    description: 'Container registry to login to'
    required: false
    default: 'ghcr.io'
  username:
    description: 'Registry username (defaults to github.actor)'
    required: false
    default: ${{ github.actor }}
  password:
    description: 'Registry password/token'
    required: true
  enable-buildx:
    description: 'Setup Docker Buildx for multi-platform builds'
    required: false
    default: 'true'
  cache-mode:
    description: 'BuildKit cache mode (min, max)'
    required: false
    default: 'max'

outputs:
  registry:
    description: 'The configured registry'
    value: ${{ inputs.registry }}
  buildx-version:
    description: 'The installed Buildx version'
    value: ${{ steps.buildx.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Set Docker environment variables
      shell: bash
      run: |
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        echo "BUILDKIT_INLINE_CACHE=1" >> $GITHUB_ENV

    - name: Setup Docker Buildx
      if: ${{ inputs.enable-buildx == 'true' }}
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        driver-opts: |
          image=moby/buildkit:latest
          network=host

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Display Docker info
      shell: bash
      run: |
        echo "Docker version: $(docker --version)"
        echo "Registry: ${{ inputs.registry }}"
        echo "BuildKit enabled: $DOCKER_BUILDKIT"
        if [ "${{ inputs.enable-buildx }}" = "true" ]; then
          echo "Buildx version: $(docker buildx version)"
          echo "Buildx platforms: $(docker buildx inspect --bootstrap | grep Platforms)"
        fi
